---
version: 3.0

nodes:
  node0:
    host:
      address: 192.168.8.49
      port: 9669
    ssh:
      address: 192.168.8.49
      port: 22
      timeout: 3s
      username: katz.zhang
      password: nebula
    services:
      graph1:
        type: graphService
        deploy_dir: deploy_dir
        runtime_dir: /home/katz.zhang/.nebula/clusters/graphd
        port: 9669
        http_port: 19669
        http_2_port: 19670
    # the following configs have default values
#    output:
#      dirPath:
#      remote:
#      logToFile:
    duration: 0s
#    period:
#    infos:
#    diags:
