---
version: 3.0

nodes:
  node0:
    host:
      address: 192.168.8.49
      port: 9669
    ssh:
      address: 192.168.8.49
      port: 22
      username: katz.zhang
      password: nebula
    # the following configs have default values
#    output:
#      dirPath:
#      remote:
#    duration:
#    interval:
#    infos:
#    diags:
