---
version: 3.0

nodes:
  node0:
    host:
      address: 192.168.8.49
      port: 9669
    ssh:
      username: katz.zhang
      password: nebula
      port: 22
    duration: -1
    interval: 0
    output: ./out/node0.log
    infos:
      - "all"
    diags:
      - "all"
  node1:
    host:
      address:
      port:
    ssh:
      username:
      password:
      port:
    duration:
    interval:
    infos:
      - "metrics"
    diags:
      - "partition"

